### ISSUE TITLE
Compatibility with pip10

### ISSUE THREAD

**Issue by butorov** [Stranger6667/pyoffers#70]
After update to pip10, I met a problem with running migrations, related with your library.
```
pip install --upgrade pip
Collecting pip
  Downloading pip-10.0.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 768kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-10.0.0
...
python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/project/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/project/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/srv/project/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/project/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/srv/project/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/Python-3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/project/src/app1/models.py", line 15, in <module>
    from app2.hasoffers.models import HOffer
  File "/srv/project/src/app2/hasoffers/models.py", line 14, in <module>
    from djoffers.models import HasOffersModel as DefaultHasOffersModel
  File "/srv/project/lib/python3.6/site-packages/djoffers/models.py", line 5, in <module>
    from pyoffers.api import HasOffersAPI
  File "/srv/project/lib/python3.6/site-packages/pyoffers/api.py", line 9, in <module>
    from .models import MANAGER_ALIASES, MODEL_MANAGERS, ApplicationManager
  File "/srv/project/lib/python3.6/site-packages/pyoffers/models/__init__.py", line 10, in <module>
    from .raw_log import RawLogManager  # noqa
  File "/srv/project/lib/python3.6/site-packages/pyoffers/models/raw_log.py", line 6, in <module>
    from pip.utils import cached_property
ModuleNotFoundError: No module named 'pip.utils'
```

Information from pypi's newsletter may be useful for you:

> In addition, the previously announced reorganisation of pip's
internals has now taken place. Unless you are the author of code that
imports the pip module (or a user of such code), this change will not
affect you. If you are affected, please report the issue to the author of the
offending code (refer them to
https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html
for the details of the announcement).

**Comment by Stranger6667** [comment]
Thank you for the bug report! It will be fixed soon
